# Generated by Django 4.0.6 on 2022-07-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_restaurant_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishes',
            options={'verbose_name': 'Страви', 'verbose_name_plural': 'Страви'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Співробітники', 'verbose_name_plural': 'Співробітники'},
        ),
        migrations.AlterModelOptions(
            name='menupositions',
            options={'verbose_name': 'Позиції меню', 'verbose_name_plural': 'Позиції меню'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Ресторан', 'verbose_name_plural': 'Ресторан'},
        ),
        migrations.AlterModelOptions(
            name='votes',
            options={'verbose_name': 'Голосування', 'verbose_name_plural': 'Голосування'},
        ),
    ]
